### ISSUE TITLE
Invalid signature error when reading file from subfolder

### ISSUE THREAD

**Issue by kadnan** [BenExile/Dropbox#1] opened 2011-12-21 18:54 UTC
Details are given here for the error. Its happening when I access file in subfolder. Things work fine if file is in parent folder.

http://pastie.org/3051012

**Comment by BenExile** [comment] 2011-12-21 20:11
It appears the problem is not related to a file being in a sub-folder, but is caused by incorrect character escaping. In this case forward slashes were encoded to %2F, but actually need to be literal forward-slash characters for use in the URL. This issue is fixed in commit 0611223ab574465f21b6130f7bd90dc225f1d330. Thanks for raising this, @kadnan. Issue closed.

**Closed as completed by BenExile** 2011-12-21 20:11 UTC
