### ISSUE TITLE
how to use with always the same dropbox, mine, and not the one of the visitor ?

### ISSUE THREAD

**Issue by matthieuc** [BenExile/Dropbox#16] opened 2012-04-12 07:26 UTC
Hello,

I can use your script, it seems very useful, and I can browse some my filders in my dropbox, but what I need to do is a webpage who display always the same folder of my Dropbox, vfor visitors, so that they can download some of my files

I wrote this script :

---

require_once('Dropbox/API.php');
require_once('Dropbox/OAuth/Consumer/ConsumerAbstract.php');
require_once('Dropbox/OAuth/Consumer/Curl.php');
require_once('Dropbox/OAuth/Storage/StorageInterface.php');
require_once('Dropbox/OAuth/Storage/Session.php');

$key      = 'xxx';  // Your Consumer Key
$secret   = 'xxx';  // Your Consumer Secret
$callback = 'my_url'; // Your Authorisation Callback URL

$storage = new \Dropbox\OAuth\Storage\Session;
$OAuth = new \Dropbox\OAuth\Consumer\Curl($key, $secret, $storage, $calllback);
$dropbox = new \Dropbox\API($OAuth);

// Upload the readme for this lib to the root of your dropbox
$dropbox->setRoot('dropbox');

$put = $dropbox->metadata($_GET['folder']);
$i=0;
while ($put->contents[$i]->path != '')
    {
    if ($put->contents[$i]->icon == 'folder')
        echo "".$put->contents[$i]->path."";
    else
        {
        echo $put->contents[$i]->path."";
        }
    $i++;
    }

---

and it works, but when I connect whit another computer, it always go to the Dropbox page for authorisation, but I don't want the visitor going to this page and I want the page use my dropbox. How can I do that? is it possible ?

I hope it's clear enough, I'm not native...

thank you

regards,

matthieu collet

**Comment by BenExile** [comment] 2012-04-18 07:52
Hi @matthieuc 

Sorry for the delayed response. I've been very busy.

What you're trying to do is possible and I have outlined the process you'll need to go through to achieve this below.

##### 1. Acquire an OAuth token

You will need to acquire an OAuth token for your Dropbox account and make this persistent. `setup.php` located in the tests directory does this already, storing the token, consumer key and secret in a serialized object written to disk. Note that `setup.php` does not make use of the Encrypter and the token is stored in plain text form - I would therefore advise that once you've obtained the OAuth token, you move it to a location outside of your web root.

##### 2. Set the OAuth token

Next you will need to set the access token on the storage handler. To do this you will need to load and unserialize the contents of the `oauth.token` file generated in the previous step:

$tokenFile = unserialize(file_get_contents('/path/to/your/token'));

You can then instantiate the storage handler as usual, then set the access token:

$storage = new \Dropbox\OAuth\Storage\Session($encrypter);
$storage->set($tokenFile->token, 'access_token');

The rest should not need any modifications, but if anything is unclear please let me know and I will assist the best I can. I hope this helps you.

**Comment by italoveloso** [comment] 2012-05-02 00:57
Hi Ben,

Following your tip I read setup.php to implement a solution to the problem mentioned. Basically I will have to authenticate local and acess_token record in a file to always read the acess_token this file to always be authenticated. Is that it?

**Comment by BenExile** [comment] 2012-05-03 10:22
Hi,

This is one way of achieving what you're trying to do. You could also implement your own storage handler, saving the token to a database and restoring in the same way.

**Comment by italoveloso** [comment] 2012-05-06 15:46
Hi Ben,

Unfortunately I could not make it work as you describe. Is there another way or can help me on this issue?

**Comment by italoveloso** [comment] 2012-05-06 18:17
Hi Ben,

Sorry about that, but I really need this feature. I was thinking of an alternative to avoid the user to be redirected to the page dropbox and what you think of the line 84 of the method ConsumerAbstract authorise make the automatic authorization with cURL? Do you think this is possible? If so how would the code? So long as I await your response and I'll now testing here. I thank your help.

**Comment by BenExile** [comment] 2012-05-09 08:55
Hi @italoveloso 

Automating the user-authorisation step defies the entire point of OAuth and I'd strongly advise against attempting to do it. The steps I provided above do work but if you're having trouble please Gist/Pastebin the code you're using and I'll see what I can do to help.

**Comment by BenExile** [comment] 2012-05-09 10:09
Hi @italoveloso 

Please contact me by email if you require any assistance with this. The issue is not with the library, but your implementation. I am closing this issue.

Regards,
Ben

**Closed as completed by BenExile** 2012-05-09 10:09 UTC
