### ISSUE TITLE
Bootstrap.php autoload function parse error

### ISSUE THREAD

**Issue by TheBlune** [BenExile/Dropbox#12] opened 2012-03-23 13:46 UTC
Hey,

I tried your accountinfo.php example and the browser returned this error concerning your autoload function:

Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in /mnt/webg/e2/24/52993124/htdocs/apis/dropbox/examples/bootstrap.php on line 24

did I set something wrong? 

I work with PHP Version 5.2.17

Thanks in advance,
Jo

**Comment by BenExile** [comment] 2012-03-23 14:10
Hi @Wannabechilean 

This library requires PHP >= 5.3.1 as described in the readme. This specific parse error is being caused by a closure (introduced in PHP 5.3).

**Comment by TheBlune** [comment] 2012-03-23 14:30
ohh no, simply overread it :D 

Sorry for stealing your time.

**Comment by BenExile** [comment] 2012-03-23 15:59
No problem :)

**Comment by TheBlune** [comment] 2012-04-10 12:58
Now with PHP Version 5.3.8 appear following errors:

arning: mcrypt_create_iv() [function.mcrypt-create-iv]: Cannot open source device in /mnt/webg/e2/24/52993124/htdocs/apis/dropbox/Dropbox/OAuth/Storage/Encrypter.php on line 53

Warning: mcrypt_encrypt() [function.mcrypt-encrypt]: The IV parameter must be as long as the blocksize in /mnt/webg/e2/24/52993124/htdocs/apis/dropbox/Dropbox/OAuth/Storage/Encrypter.php on line 54

Notice: unserialize() [function.unserialize]: Error at offset 0 of 16 bytes in /mnt/webg/e2/24/52993124/htdocs/apis/dropbox/Dropbox/OAuth/Storage/Encrypter.php on line 69

**Comment by BenExile** [comment] 2012-04-10 18:32
Hi @Wannabechilean 

It seems PHP is unable to read from /dev/random (MCRYPT_DEV_RANDOM). Please check the permissions on /dev/random and /dev/urandom (see below) ensuring it is readable by the user/group PHP is running as.

Also, please pull the changes on master. I committed a small change yesterday where MCRYPT_DEV_RANDOM was changed to MCRYPT_DEV_URANDOM to fix a slow encryption/decryption bug.

**Comment by lincolnbrito** [comment] 2012-05-10 18:43
I use PHP 5.3.6 but the same error is returned in line 24

**Comment by BenExile** [comment] 2012-05-10 21:20
Hi @lincolnbrito 

Can you give me some more details about your platform? Have you checked the permissions to ensure MCRYPT_DEV_URANDOM/MCRYPT_DEV_RANDOM is readable? Also please see the docs page for [mcrypt_create_iv](http://php.net/manual/en/function.mcrypt-create-iv.php) and try other sources to see if this problem persists - to modify the IV source you will need to change `IV_SOURCE` [here](https://github.com/BenTheDesigner/Dropbox/blob/master/Dropbox/OAuth/Storage/Encrypter.php#L20). 

Hope this helps :)

**Comment by lincolnbrito** [comment] 2012-05-11 13:49
Windows 7, Xampp 1.7.5, PHP 5.3.6 

The error:
Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in .../bootstrap.php on line 24

**Comment by BenExile** [comment] 2012-05-11 15:21
Hi @lincolnbrito 

I am looking into this as anonymous functions were introduced in PHP 5.3.0. I'm unable to replicate at present but will do what I can to help.

**Comment by BenExile** [comment] 2012-05-16 16:22
As I'm unable to replicate this issue and you are the only person experiencing the problem I am going to have to close it. Please feel free to email me with any more relevant details and I will be happy to look at it again.

**Closed as completed by BenExile** 2012-05-16 16:22 UTC

**Comment by itkikok** [comment] 2012-06-06 05:38
Hello @BenTheDesigner  I use fedrora 16, php 5.3.13 .   I have error line 24 
error 
Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in .../bootstrap.php on line 24

same @lincolnbrito

**Comment by ghost** [comment] 2013-06-03 14:47
Hi! I know this problem has been closed but maybe now you know the solution...
I use php 6 with appserv and have this message: Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in .../bootstrap.php on line 28

In that line as you know is: 

// Register a simple autoload function
spl_autoload_register(function($class){
    $class = str_replace('\', '/', $class);
    require_once('../' . $class . '.php');
});

If you know what is the solution please help us.!!

Thak you so much.

**Comment by BenExile** [comment] 2013-06-03 14:51
Hi @Suhkha 

PHP 6 has not been released yet. Can you please confirm your PHP version and that your install meets the requirements detailed in the readme?

**Comment by ghost** [comment] 2013-06-03 15:07
You're right. Sorry but in my php info says: PHP Version 6.0.0-dev, but is > 5.2 (don't have this)
And I readed the 'readme' and I think followed the steps.

(Sorry for my english).

**Comment by BenExile** [comment] 2013-06-03 15:36
Hi @Suhkha 

Because you're on a development version it could well be a bug with that. Are you able to test on another machine with a stable (or at least RC) version of PHP installed?

For compatibility with PHP < 5.3, lines 24-27 in examples/boostrap.php can be changed to the following but you will encounter other issues which is why 5.3.1 is a requirement (cURL issues with named file uploads, and some other small issues).

``` php
// Simple autoload function
function autoload_function($class){
    $class = str_replace('\\', '/', $class);
    require_once('../' . $class . '.php');
}

// Register the autoload function
spl_autoload_register('autoload_function');
```

**Comment by ghost** [comment] 2013-06-03 15:48
For now I don't have another machine, just one but is x86.

I think I coud install another server or change the version of php.

Thank you.!
When testing this I will comment.
:)

**Comment by Bugster** [comment] 2013-06-03 16:22
This line:
$class = str_replace('\', '/', $class);

You typed \'

Repace that with \'
